# Generated by Django 5.1.4 on 2024-12-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
